---
steps:
  - name: Extract Manifest values
    id: manifest
    uses: pietrobolcato/action-read-yaml@1.0.0
    with:
      config: ${{ github.workspace }}/${MANIFEST}
    env:
      MANIFEST: ((cf_manifest))
  - name: Install Cloud Foundry CLI
    run: |
      mkdir cf-cli
      cd cf-cli
      curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=v8&source=github" | tar -zx
      rm cf
      mv cf8 cf
      chmod +x cf
      echo ${{ steps.manifest.outputs['applications.0.name'] }}
      echo ${{ steps.manifest.outputs[] }}
  - name: Deploy
    run: |
      cf-cli/cf api $API
      cf-cli/cf auth
      cf-cli/cf target -o $ORG -s $SPACE
      cf-cli/cf push -f $MANIFEST --strategy rolling
      app_name=${{ steps.manifest.outputs['applications.0.name'] }}
      cf-cli/cf set-label app $app_name "commit=${{ github.sha }}"
    env:
      API: ((cf_api))
      CF_USERNAME: ((cf_username))
      CF_PASSWORD: ((cf_password))
      ORG: ((cf_org))
      SPACE: ((cf_space))
      MANIFEST: ((cf_manifest))
