---
steps:
  - name: Extract Manifest values
    id: manifest
    uses: pietrobolcato/action-read-yaml@1.0.0
    with:
      config: ${{ github.workspace }}/${MANIFEST}
    env:
      MANIFEST: ((cf_manifest))
  - name: Install Cloud Foundry CLI
    run: |
      curl -L -f "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=v8&source=github" --output cf.tgz
      tar -xvzf cf.tgz
      ls -al
      pwd
      chmod +x cf
      ls -al
  - name: Deploy
    run: |
      cf api $API
      cf auth
      cf target -o $ORG -s $SPACE
      cf push -f $MANIFEST --strategy rolling
      app_name=${{ steps.manifest.outputs['applications.name'] }}
      cf set-label app $app_name "commit=${{ github.sha }}"
    env:
      API: ((cf_api))
      CF_USERNAME: ((cf_username))
      CF_PASSWORD: ((cf_password))
      ORG: ((cf_org))
      SPACE: ((cf_space))
      MANIFEST: ((cf_manifest))
