fail_on_severity: critical
allow_licenses: [GPL-3.0, BSD-3-Clause, MIT]
fail_on_scopes: runtime
# allow-ghsas: Contains a list of GitHub Advisory Database IDs that can be skipped during detection. https://github.com/advisories
license_check: true
vulnerability_check: true
comment_summary_in_pr: true
