fail-on-severity: critical
allow-licenses: GPL-3.0, BSD-3-Clause, MIT
fail-on-scopes: runtime
# allow-ghsas: Contains a list of GitHub Advisory Database IDs that can be skipped during detection. https://github.com/advisories
license-check: true
vulnerability-check: true
comment-summary-in-pr: true
