---
name: Development
on:
  push:
    branches:
      - main
    paths: ((build_paths))
    ignore_paths:
      - development-version.txt
      - production-version.txt
  workflow_dispatch:
jobs:
  unit-test:
    name: Unit Test
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - skylounge-step: unit-test
  build:
    needs: unit-test
    name: Build Container Image
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    env:
      REGISTRY: ((registry_url))
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Set image name
        run: |
          echo "IMAGE_NAME=${{ env.REGISTRY }}/${{ github.event.repository.name }}:${{ github.sha }}" >> $GITHUB_ENV
      - skylounge-step: cloud-auth
      - skylounge-step: build-container-image
      - skylounge-step: push-container-image
      - skylounge-step: upload-sboms
  deploy: skylounge-job
  owasp-zap-full-scan:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: OWASP Zap Full Scan
        uses: zaproxy/action-full-scan@v0.4.0
        id: scan
        with:
          target: ((endpoint_to_scan))
          rules_file_name: skylounge/owasp/rules.cfg
          issue_title: "OWASP Full Scan - ${{ github.run_number }}"
          token: ${{ github.token }}
          fail_action: false
  integration-test: skylounge-job
  artifact-version:
    needs: [owasp-zap-full-scan, integration-test]
    name: Update artifact version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Update Artifact Version
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          echo "${{ github.sha }}" > development-version.txt
          git add development-version.txt
          git commit -m "update development version: ${{ github.sha }}"
          git pull --rebase
          git push
