---
name: Development
on:
  push:
    branches:
      - main
    paths: ((build_paths))
    ignore_paths:
      - development-version.txt
      - production-version.txt
  workflow_dispatch:
jobs:
  unit-test:
    name: Unit Test
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - skylounge-step: unit-test
  build:
    needs: unit-test
    name: Build Container Image
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    env:
      REGISTRY: ((registry_url))
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Set image name
        run: |
          echo "IMAGE_NAME=${{ env.REGISTRY }}/${{ github.event.repository.name }}:${{ github.sha }}" >> $GITHUB_ENV
      - skylounge-step: cloud-auth
      - skylounge-step: build-container-image
      - skylounge-step: push-container-image
      - skylounge-step: upload-sboms
