name: Pull Request
on:
  pull_request:
    types: [opened, reopened]
    paths: ((build_paths))

permissions:
  contents: read
  pull_request: write

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - skylounge-step: unit-test
  dependency-review:
    name: GitHub Dependency Review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Dependency Review
        uses: actions/dependency-review-action@v3
        with:
          config-file: ${{ env.CONFIG_FILE }}
          external-repo-token: ${{ env.EXTERNAL_REPO_TOKEN }}
        env:
          CONFIG_FILE: ((config_file))
          EXTERNAL_REPO_TOKEN: ((external_repo_token))
