name: Scan Pull Request
on: [pull_request]

permissions:
  contents: read
  pull-request: write

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - skylounge-step: unit-test
  dependency-review:
    name: GitHub Dependency Review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Dependency Review
        uses: actions/dependency-review-action@v3
        with:
          config-file: ((config_file))
          external-repo-token: ((external_repo_token))
