name: Pull Request
on:
  pull_request:
    types: [opened, reopened]
    paths: ((build_paths))

permissions:
  contents: read
  pull-requests: write

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - skylounge-step: unit-test
  dependency-review:
    name: GitHub Dependency Review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: sky-lounge/skylounge-library
          path: library
          token: ${{ secrets.LIBRARY_TOKEN }}
      - name: debug
        run: |
          cat library/jobs/github/security/dependency-review/config/cloud-gov.yml
      - name: Dependency Review
        uses: actions/dependency-review-action@v3
        with:
          config-file: ${{ env.CONFIG_FILE }}
          external-repo-token: ${{ secrets.LIBRARY_TOKEN }}
        env:
          CONFIG_FILE: ((config_file))
