deploy:
  needs: build
  name: Deploy to Google Cloud Run
  runs-on: ubuntu-latest
  env:
    REGISTRY: ((registry_url))
    GCP_PROJECT: ((gcp_project))
  steps:
    - name: Checkout branch
      uses: actions/checkout@v3
      with:
        path: source
    - name: Set image and service name
      run: |
        sed -i -e 's%${IMAGE_NAME}%'"$IMAGE_NAME"'%g' source/service.yaml
        sed -i -e 's%${GCP_PROJECT}%'"$GCP_PROJECT"'%g' source/service.yaml
      env:
        IMAGE_NAME: "${{ env.REGISTRY }}/${{ github.event.repository.name }}:${{ github.sha }}"
    - id: auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ((credentials_json_secret_string))
    - id: deploy
      name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v0
      with:
        metadata: source/service.yaml
