params:
  tf_state_bucket: # The name of the Google Cloud Storage bucket to store terraform state. Example: tfstate.skylounge.dev
  dns_zone_name: # The zone name in Google DNS where to configure the domain mapping. Example: skyloungedev
  cloud_run_location: # The location where your application is deployed. Example: us-central1
  cloud_run_invoker: # OPTIONAL - The name of the user allowed to invoke your Cloud Run service. For any authenticated Google user, use `allUsers`. For public access, leave it empty. Example: allUsers
