---
name: Production

on:
  push:
    branches:
      - ((main_branch))
    paths:
      - .github/production-version.txt
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy to production space
    runs-on: ubuntu-latest
    outputs:
      route: ${{ steps.deploy.outputs.route }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - skylounge-step: pre-deploy
      - skylounge-step: deploy
