---
name: Production Scans
on:
  schedule:
    - cron: ((cron_schedule))
  workflow_dispatch: # allow manual trigger
jobs:
  owasp-zap-full-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Run OWASP Zap full scan
        uses: zaproxy/action-full-scan@v0.11.0
        id: scan
        with:
          target: ((endpoint_to_scan))
          rules_file_name: skylounge/owasp/rules.cfg
          issue_title: "Daily Scans - OWASP Full Scan - ${{ github.run_number }}"
          token: ${{ github.token }}
          fail_action: false
  dependency-review:
    name: GitHub Dependency Review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Dependency Review
        uses: actions/dependency-review-action@main
        with:
          config-file: ${{ env.CONFIG_FILE }}
          external-repo-token: ${{ secrets.LIBRARY_TOKEN }}
        env:
          CONFIG_FILE: ((config_file))
