deploy:
  needs: build
  name: Deploy to Cloud Foundry
  runs-on: ubuntu-latest
  env:
    REGISTRY: ((registry_url))
  steps:
    - name: Checkout branch
      uses: actions/checkout@v3
    - name: Set image and service name
      run: |
        sed -i -e 's%${IMAGE_NAME}%'"$IMAGE_NAME"'%g' ./service.yaml
        sed -i -e 's%${GCP_PROJECT}%'"$GCP_PROJECT"'%g' ./service.yaml
      env:
        IMAGE_NAME: "${{ env.REGISTRY }}/${{ github.event.repository.name }}:${{ github.sha }}"
        GCP_PROJECT: ((gcp_project))
    - id: auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: "${{ secrets.GOOGLE_CREDENTIALS_DEV }}"
    - id: deploy
      uses: google-github-actions/deploy-cloudrun@v0
      with:
        metadata: ./service.yaml
